# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

notifications:
  email:
    recipients:
      - elbenjakobjul@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

after_success:
    - Rscript -e 'covr::codecov()'
